# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "652de796d30d0744b30d300a9eff22fd"
name = "flora-plugin"
application_url = "http://localhost:3000"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "https://arrivals-usgs-offering-colours.trycloudflare.com/webhooks/orders-create"
  

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_fulfillments,write_merchant_managed_fulfillment_orders,write_products,write_third_party_fulfillment_orders"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "http://localhost:3000/callback",
  "http://localhost:3000/shopify/callback"
]
